env:
    MANIFEST: https://github.com/PixelExperience/manifest -b thirteen
    DEVICE: oscar
    OEM: oneplus
    DT_LINK: https://github.com/OnePlus-sm6375-devices/device_oneplus_oscar.git
    DT_PATH: device/oneplus/oscar
    VT_LINK: https://github.com/phhgsi/vendor_oneplus_oscar.git
    VT_PATH: vendor/oneplus/oscar
    KT_LINK: https://github.com/OnePlus-sm6375-devices/android_kernel_oneplus_sm6375.git
    PLATFORM: sm6375
    KT_PATH: kernel/oneplus/sm6375
    CT_LINK: https://github.com/OnePlus-sm6375-devices/android_device_oneplus-sm6375-common.git
    CT_PATH: device/oneplus/sm6375-common
    HT_LINK: https://github.com/LineageOS/android_hardware_oneplus.git
    HT_PATH: hardware/oneplus
    OCT_LINK: https://github.com/OnePlus-sm6375-devices/android_device_oneplus_oscar-kernel.git
    OCT_PATH: device/oneplus/oscar-kernel

    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: lineage_oscar-userdebug
    OUTPUT: PixelExperience*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache clang -y
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "ajaysinghx"
       - git config --global user.email "vipvijayadav@gmail.com"
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init -u https://github.com/PixelExperience/manifest -b thirteen
      - repo sync -j31 --force-sync --no-tags --no-clone-bundle
      - git clone https://github.com/OnePlus-sm6375-devices/device_oneplus_oscar.git device/oneplus/oscar
      - git clone https://github.com/phhgsi/vendor_oneplus_oscar.git vendor/oneplus/oscar
      - git clone https://github.com/OnePlus-sm6375-devices/android_kernel_oneplus_sm6375.git kernel/oneplus/sm6375
      - git clone https://github.com/OnePlus-sm6375-devices/android_device_oneplus-sm6375-common.git device/oneplus/sm6375-common
      - git clone https://github.com/LineageOS/android_hardware_oneplus.git hardware/oneplus
      - git clone https://github.com/OnePlus-sm6375-devices/android_device_oneplus_oscar-kernel.git device/oneplus/oscar-kernel
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
     
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch "lineage_oscar-userdebug"
      - make bacon
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"oscar"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo PixelExperience*.zip) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

