
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - cd ~
      
      - mkdir -p ~/ajay 
      - cd ~/ajay 
   
      - git clone https://github.com/ShivamKumarJha/android_tools.git
      - cd ~/android_tools
      - chmod +x setup.sh
      - sudo bash setup.sh
      
      - mkdir -p ~/aj 
      - cd ~/aj
      - git clone https://dumps.tadiphone.dev/dumps/oneplus/op535dl1.git
      
      - cd ~
      - cd ~/ajay
      - cd ~/android_tools
      - ./tools/dummy_dt.sh ../aj

